# Generated by Django 2.2 on 2020-02-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customer_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='profession',
        ),
        migrations.AddField(
            model_name='customer',
            name='profession',
            field=models.ManyToManyField(default='', to='core.Profession'),
        ),
    ]
